name: metro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:

  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  qr_flutter: ^4.0.0
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  equatable: ^2.0.7
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.10

flutter:
  uses-material-design: true
  
  assets:
    - images/CairoMetroMap.png
    - images/dalil.png
    - images/dalilW.png
    - images/Details.png
    - images/gps.png
    - images/myticket.png
    - images/sun.png
    - images/home.png
    - images/station.png
    - images/arrow.png
    - lib/l10n/ # أضف هذا السطر ليشمل ملفات الترجمة

  fonts:
    - family: Montserrat-Arabic-Regular
      fonts:
        - asset: fonts/Montserrat-Arabic-Regular.ttf