// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqPZMuoUrtVjp3nA1iLyJwPvAvXjcVo4U',
    appId: '1:919183894768:web:ebb53b7d23d3fafe173a35',
    messagingSenderId: '919183894768',
    projectId: 'dalil-b6619',
    authDomain: 'dalil-b6619.firebaseapp.com',
    storageBucket: 'dalil-b6619.firebasestorage.app',
    measurementId: 'G-1VKGVQDRFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrbYNy9VPGnhQBISbUeCR-8jp9C773zBs',
    appId: '1:919183894768:android:c7cfa9c744823628173a35',
    messagingSenderId: '919183894768',
    projectId: 'dalil-b6619',
    storageBucket: 'dalil-b6619.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7UN2I7LG0CG4Y7xAxaCGp8hrq3m2tvEw',
    appId: '1:919183894768:ios:14c32e6de6d2e8ce173a35',
    messagingSenderId: '919183894768',
    projectId: 'dalil-b6619',
    storageBucket: 'dalil-b6619.firebasestorage.app',
    iosBundleId: 'com.example.dalil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7UN2I7LG0CG4Y7xAxaCGp8hrq3m2tvEw',
    appId: '1:919183894768:ios:14c32e6de6d2e8ce173a35',
    messagingSenderId: '919183894768',
    projectId: 'dalil-b6619',
    storageBucket: 'dalil-b6619.firebasestorage.app',
    iosBundleId: 'com.example.dalil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqPZMuoUrtVjp3nA1iLyJwPvAvXjcVo4U',
    appId: '1:919183894768:web:63d5b5cee67b19b4173a35',
    messagingSenderId: '919183894768',
    projectId: 'dalil-b6619',
    authDomain: 'dalil-b6619.firebaseapp.com',
    storageBucket: 'dalil-b6619.firebasestorage.app',
    measurementId: 'G-121VETF4DH',
  );
}
